module.exports = (sequelize, DataTypes) => {
    const Imobiliario = sequelize.define('imobiliario', {
        codigo: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        proposta:DataTypes.STRING, 
        data_solicitacao:DataTypes.STRING, 
        linha_credito:DataTypes.STRING, 
        valor_financiado:DataTypes.STRING, 
        situacao_sac:DataTypes.STRING, 
        status:DataTypes.STRING, 
        data_atualizacao:DataTypes.STRING, 
        responsavel:DataTypes.STRING, 
        nome_operador:DataTypes.STRING, 
        parceiro:DataTypes.STRING, 
        supervisor:DataTypes.STRING, 
        gerente:DataTypes.STRING, 
        nome:DataTypes.STRING, 
        rg:DataTypes.STRING, 
        data_expedicao:DataTypes.STRING, 
        cpf:DataTypes.STRING, 
        telefone:DataTypes.STRING, 
        email:DataTypes.STRING, 
        casado:DataTypes.STRING, 
        nome1:DataTypes.STRING, 
        rg1:DataTypes.STRING, 
        data_expedicao1:DataTypes.STRING, 
        cpf1:DataTypes.STRING, 
        telefone1:DataTypes.STRING, 
        email1:DataTypes.STRING, 
        renda:DataTypes.STRING, 
        arquivo1:DataTypes.STRING, 
        arquivo2:DataTypes.STRING, 
        arquivo3:DataTypes.STRING, 
        arquivo4:DataTypes.STRING, 
        nome2:DataTypes.STRING, 
        nome3:DataTypes.STRING, 
        nome4:DataTypes.STRING, 
        rg2:DataTypes.STRING, 
        rg3:DataTypes.STRING, 
        rg4:DataTypes.STRING, 
        data_expedicao2:DataTypes.STRING, 
        data_expedicao3:DataTypes.STRING, 
        data_expedicao4:DataTypes.STRING, 
        cpf2:DataTypes.STRING, 
        cpf3:DataTypes.STRING, 
        cpf4:DataTypes.STRING, 
        telefone2:DataTypes.STRING, 
        telefone3:DataTypes.STRING, 
        telefone4:DataTypes.STRING, 
        email2:DataTypes.STRING, 
        email3:DataTypes.STRING, 
        email4:DataTypes.STRING, 
        correntista:DataTypes.STRING, 
        tipo_imovel:DataTypes.STRING, 
        imovel:DataTypes.STRING, 
        sub_status:DataTypes.STRING, 
        supervisor_usuario:DataTypes.STRING, 
        tipo_correntista:DataTypes.STRING, 
        data_envio:DataTypes.STRING, 
        mes:DataTypes.STRING, 
        arquivo5:DataTypes.STRING, 
        arquivo6:DataTypes.STRING, 
        arquivo7:DataTypes.STRING, 
        arquivo8:DataTypes.STRING, 
        arquivo9:DataTypes.STRING, 
        arquivo10:DataTypes.STRING, 
        renda1:DataTypes.STRING, 
        observacao:DataTypes.STRING,
        arquivo21:DataTypes.STRING, 
        arquivo22:DataTypes.STRING, 
        uf:DataTypes.STRING, 
        arquivo_rc:DataTypes.STRING, 
        supervisor_operador:DataTypes.STRING, 
        telefone_alternativo:DataTypes.STRING, 
        id_parceiro:DataTypes.STRING, 
        banco:DataTypes.STRING, 
        data_ag:DataTypes.STRING, 
        horario:DataTypes.STRING, 
        modulo:DataTypes.STRING, 
        modalidade:DataTypes.STRING, 
        identificacao_imovel:DataTypes.STRING, 
        data_nascimento:DataTypes.STRING, 
        telefone_promotor:DataTypes.STRING, 
        autorizacao:DataTypes.STRING, 
        data_retorno:DataTypes.STRING
    }, {
        tableName: 'imobiliario',
        timestamps: false
    })
    return Imobiliario;
};