module.exports = (sequelize, DataTypes) => {
    const Sigla = sequelize.define('siglae', {
        codigo: {
            type: DataTypes.INTEGER,
            primaryKey: true
        },
            sigla_e:DataTypes.STRING, 
            cpf_sigla:DataTypes.STRING, 
            codigo_corban:DataTypes.STRING, 
            corban:DataTypes.STRING, 
            nome_corban:DataTypes.STRING, 
            sigla_prospect:DataTypes.STRING, 
            certificacao:DataTypes.STRING, 
            data_certificacao:DataTypes.STRING, 
            status_i:DataTypes.STRING, 
            cpf_usuario1:DataTypes.STRING, 
            cpf_usuario2:DataTypes.STRING, 
            cpf_usuario3:DataTypes.STRING, 
            cpf_usuario4:DataTypes.STRING, 
            cpf_usuario5:DataTypes.STRING, 
            usa_sigla1:DataTypes.STRING, 
            usa_siglai1:DataTypes.STRING, 
            usa_esteira1:DataTypes.STRING, 
            status_e:DataTypes.STRING,
            observacao:DataTypes.STRING,
            data_cadastro:DataTypes.STRING, 
            usa_sigla2:DataTypes.STRING, 
            usa_sigla3:DataTypes.STRING, 
            usa_sigla4:DataTypes.STRING, 
            usa_sigla5:DataTypes.STRING, 
            usa_siglai2:DataTypes.STRING, 
            usa_siglai3:DataTypes.STRING, 
            usa_siglai4:DataTypes.STRING, 
            usa_siglai5:DataTypes.STRING, 
            usa_esteira2:DataTypes.STRING, 
            usa_esteira3:DataTypes.STRING, 
            usa_esteira4:DataTypes.STRING, 
            usa_esteira5:DataTypes.STRING, 
            responsavel:DataTypes.STRING, 
            data_atualizacao:DataTypes.STRING, 
            arquivo1:DataTypes.STRING, 
            arquivo2:DataTypes.STRING, 
            arquivo3:DataTypes.STRING, 
            arquivo4:DataTypes.STRING, 
            arquivo5:DataTypes.STRING, 
            arquivo6:DataTypes.STRING, 
            arquivo7:DataTypes.STRING, 
            arquivo8:DataTypes.STRING, 
            data_inativacao:DataTypes.STRING, 
            motivo_pendencia:DataTypes.STRING
    }, {
        tableName: 'siglae',
        timestamps: false
    })
    return Sigla;
};